title: Meghan Tole
description: A blog devoted to feature writing
footer_text: Copyright 2021 Meghan Tole
header_feature_image: ../uploads/jdjdjdjd.png
header_text: Writing So You Don't Have To
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/img_3766-2.jpg
favicon: ../uploads/jdjdjdjd.png
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme
    tab: false
