title: MeghaFont
description: Website about typography
footer_text: Copyright 2021 Meghan Tole
header_feature_image: ../uploads/photo-1503694978374-8a2fa686963a.jpeg
header_text: Typography & Print Media
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/jjjj.png
favicon: ../uploads/jjjj.png
gridlayout: true
fixednavbar: true
upzoom: true
