title: MEGHAFONT
description: Website about typography
footer_text: Copyright 2021 Meghan Tole
header_feature_image: ../uploads/sincerely-media-wnmonqihpwq-unsplash.jpg
header_text: MEGHAFONT
header_text_color: "#d2bb50"
bannerheight: 40vmax
navbarheight: 35px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
