title: MeghaFont
description: Website about typography
footer_text: Copyright 2021 Meghan Tole
header_feature_image: ../uploads/photo-1503694978374-8a2fa686963a.jpeg
header_text: Typography in Print Publications
header_text_color: "#fcebff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/jjjjj.jpg
favicon: ../uploads/jjjjj.jpg
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme
    tab: false
